"""empty message

Revision ID: 9aa2401e22de
Revises: faf295cc341f
Create Date: 2022-02-08 01:19:22.961842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa2401e22de'
down_revision = 'faf295cc341f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises_tracker', sa.Column('exercise_id', sa.Integer(), nullable=False))
    op.drop_constraint('exercises_tracker_esercise_id_fkey', 'exercises_tracker', type_='foreignkey')
    op.create_foreign_key(None, 'exercises_tracker', 'exercise', ['exercise_id'], ['id'])
    op.drop_column('exercises_tracker', 'esercise_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises_tracker', sa.Column('esercise_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exercises_tracker', type_='foreignkey')
    op.create_foreign_key('exercises_tracker_esercise_id_fkey', 'exercises_tracker', 'exercise', ['esercise_id'], ['id'])
    op.drop_column('exercises_tracker', 'exercise_id')
    # ### end Alembic commands ###
