"""empty message

Revision ID: faf295cc341f
Revises: bcfd4649749b
Create Date: 2022-02-04 20:59:52.947287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf295cc341f'
down_revision = 'bcfd4649749b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=280), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises_tracker',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('esercise_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['esercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'esercise_id')
    )
    op.add_column('food', sa.Column('proteins', sa.Integer(), nullable=True))
    op.drop_column('food', 'prots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('prots', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('food', 'proteins')
    op.drop_table('exercises_tracker')
    op.drop_table('exercise')
    # ### end Alembic commands ###
